/users:
  get:
    summary: Get all users (from MongoDB)
    description: Returns all stored user bookings directly from MongoDB.
    responses:
      '200':
        description: List of users
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: string
                  name:
                    type: string
                  destination:
                    type: string
                  age:
                    type: integer
                  nameOfNextOfKin:
                    type: string
                  phoneNumberOfNextKin:
                    type: integer
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
                  __v:
                    type: integer
            examples:
              Example1:
                summary: User booking - Adefisa Babatunde
                value:
                  _id: 68a4cc0801ce370ca2937bd6
                  name: Adefisa Babatunde
                  destination: Kano State
                  age: 18
                  nameOfNextOfKin: Sola
                  createdAt: 2025-08-19T19:10:00.677Z
                  updatedAt: 2025-08-19T19:10:00.677Z
                  __v: 0
              Example2:
                summary: User booking - Adefisa Babatunde
                value:
                  _id: 68a4cedd75a2789fd8c175d6
                  name: Adefisa Babatunde
                  destination: Kano State
                  age: 18
                  nameOfNextOfKin: Sola
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T19:22:05.522Z
                  updatedAt: 2025-08-19T19:22:05.522Z
                  __v: 0
              Example3:
                summary: User booking - Adefisa Babatunde
                value:
                  _id: 68a4d31475a2789fd8c175d8
                  name: Adefisa Babatunde
                  destination: Kano State
                  age: 18
                  nameOfNextOfKin: Sola
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T19:40:04.428Z
                  updatedAt: 2025-08-19T19:40:04.428Z
                  __v: 0
              Example4:
                summary: User booking - Adefisa Babatunde
                value:
                  _id: 68a4d35aa6da93e62c90fd15
                  name: Adefisa Babatunde
                  destination: Kano State
                  age: 18
                  nameOfNextOfKin: Sola
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T19:41:14.795Z
                  updatedAt: 2025-08-19T19:41:14.795Z
                  __v: 0
              Example5:
                summary: User booking - Adefisa Babatunde
                value:
                  _id: 68a4d60ea6da93e62c90fd17
                  name: Adefisa Babatunde
                  destination: Kano State
                  age: 18
                  nameOfNextOfKin: Sola
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T19:52:46.292Z
                  updatedAt: 2025-08-19T19:52:46.292Z
                  __v: 0
              Example6:
                summary: User booking - Ayoola James
                value:
                  _id: 68a508e40756528053dc8e9e
                  name: Ayoola James
                  destination: Niger State
                  age: 22
                  nameOfNextOfKin: Bimpe
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T23:29:40.428Z
                  updatedAt: 2025-08-19T23:29:40.428Z
                  __v: 0
              Example7:
                summary: User booking - Sola Kazeem
                value:
                  _id: 68a5094f0756528053dc8ea0
                  name: sola kazeem
                  destination: Bauchi State
                  age: 25
                  nameOfNextOfKin: Bimpe
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T23:31:27.395Z
                  updatedAt: 2025-08-19T23:31:27.395Z
                  __v: 0
              Example8:
                summary: User booking - Boluwatife Eleyele
                value:
                  _id: 68a509af0756528053dc8ea2
                  name: Boluwatife Eleyele
                  destination: Borno State
                  age: 24
                  nameOfNextOfKin: Peter
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T23:33:03.519Z
                  updatedAt: 2025-08-19T23:33:03.519Z
                  __v: 0
              Example9:
                summary: User booking - Peter Eleyele
                value:
                  _id: 68a509d60756528053dc8ea4
                  name: Peter Eleyele
                  destination: Kebbi State
                  age: 24
                  nameOfNextOfKin: Boluwatife
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T23:33:42.062Z
                  updatedAt: 2025-08-19T23:33:42.062Z
                  __v: 0
              Example10:
                summary: User booking - Peter Eleyele
                value:
                  _id: 68a50aab0756528053dc8ea6
                  name: Peter Eleyele
                  destination: Kebbi State
                  age: 24
                  nameOfNextOfKin: Boluwatife
                  phoneNumberOfNextKin: 8116358044
                  createdAt: 2025-08-19T23:37:15.302Z
                  updatedAt: 2025-08-19T23:37:15.302Z
                  __v: 0
